alias: 'Alarm Triggered'
hide_entity: True
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: 'triggered'
action:
  - service: switch.turn_on
    entity_id: switch.everspring_se812_siren_switch_3_0
