alias: 'Alarm Disarmed'
hide_entity: True
trigger:
  - platform: state
    entity_id: alarm_control_panel.alarm
    to: 'disarmed'
action:
  - service: switch.turn_off
    entity_id: switch.everspring_se812_siren_switch_3_0
  - service: notify.email
    data:
      title: 'Unit Alarm Disarmed'
      message: 'Unit Alarm Disarmed' 
