alias: Publish Motion Rear 
hide_entity: True   
trigger:
  platform: state
  entity_id: sensor.aeotec_zw100_multisensor_6_burglar_6_10
action:
  - service: mqtt.publish
    data:
      topic: "unit/rearmotion"
      payload_template: "{{ states('sensor.aeotec_zw100_multisensor_6_burglar_6_10') }}"
      retain: "true"
