alias: Publish Temp Front Door
hide_entity: True
trigger:
  platform: state
  entity_id: sensor.aeotec_zw100_multisensor_6_temperature_2_1
action:
  - service: mqtt.publish
    data:
      topic: "unit/fronttemp"
      payload_template: "{{ states('sensor.aeotec_zw100_multisensor_6_temperature_2_1') }}"
      retain: "true"
